Add more supported attributes to MarkdownText
jeziellago/compose-markdown pull request #1
Opened 2021-03-06 22:01 UTC by THEAccess

This PR adds the following attributes (parameters) to MarkdownText: textColor, fontSize, letterSpacing, textAlign, maxLines, style, Update README.

2021-03-07 19:13 UTC, jeziellago requested changes

2021-03-07 19:13 UTC, jeziellago commented on markdowntext/src/main/java/dev/jeziellago/compose/markdowntext/MarkdownText.kt
> +        }
Should be simplified:
```suggestion
        when (textAlign) {
            TextAlign.Left, TextAlign.Start -> View.TEXT_ALIGNMENT_TEXT_START
            TextAlign.Right, TextAlign.End -> View.TEXT_ALIGNMENT_TEXT_END
            TextAlign.Center -> View.TEXT_ALIGNMENT_CENTER
            else -> null
        }?.let { align ->
            textAlignment = align
        }
```

2021-03-07 19:13 UTC, jeziellago commented on markdowntext/src/main/java/dev/jeziellago/compose/markdowntext/MarkdownText.kt
> +        if(mergedStyle.letterSpacing.type != TextUnitType.Unspecified) setLetterSpacing(mergedStyle.letterSpacing.value)
`setLetterSpacing` only accepts value in `em` unit.
If the `type` in `mergedStyle.letterSpacing.type` isn't `TextUnitType.Em`, the letterSpacing will be wrong.

2021-03-07 19:13 UTC, jeziellago commented on README.md
> +The font can be changed by passing a font xml resource as `fontResource` parameter.
Could you put a code snippet here (as an example)?

2021-03-09 11:36 UTC, jeziellago commented on markdowntext/build.gradle
> +                version = '1.0.0-alpha01'
Publication configs mustn't be modified.

2021-03-09 11:54 UTC, THEAccess commented on markdowntext/build.gradle
> +                version = '1.0.0-alpha01'
Must have slipped through. Was for internal purposes only. I'll revert that

2021-03-11 11:55 UTC, jeziellago commented
Update your branch with `0.2.0` to solve conflicts in `sample/src/main/java/dev/jeziellago/compose/markdown/MainActivity.kt`

2021-03-12 11:04 UTC, jeziellago approved these changes

2021-03-12 11:04 UTC, merged