Fix Issue #85
jeziellago/compose-markdown pull request #96
Opened 2024-06-23 09:42 UTC by HXavier21

Fix #85 by adding a CustomTextView, which will continue passing the event to other components when there is no link clicked.
Thus the below code can word as well:
```kotlin
MarkdownText(
    markdown = """
           ---
            __Advertisement :)__
            
            - __[nodeca](https://nodeca.github.io/pica/demo/)__ - high quality and fast image
              resize in browser.
            - __[babelfish](https://github.com/nodeca/babelfish/)__ - developer friendly
              i18n with plurals support and easy syntax.
            
            You will like those projects!
            
            ---
        """.trimIndent(),
    modifier = Modifier.pointerInput(Unit) {
        detectTapGestures(onLongPress = {
            Toast
                .makeText(this@MainActivity, "On long press", Toast.LENGTH_SHORT)
                .show()
        })
    }
)
```

2024-06-26 14:49 UTC, jeziellago requested changes
Hi @HXavier21, thanks for contributing!
I appreciate your contribution, however there are some opportunities to improve. 
1. All code should be written in Kotlin
2. Every change should provide backward compatibility, it means code being removed/deleted usually force the library users to change their code when update
I understand your use case, but we should think in other use cases that might break when a new change is introduced.

2024-07-11 18:48 UTC, jeziellago commented on markdowntext/src/main/java/dev/jeziellago/compose/markdowntext/CustomTextView.kt
> +class CustomTextView(context: Context?) : AppCompatTextView(context!!) {
The `Context` here should be required.
```suggestion
class CustomTextView(context: Context) : AppCompatTextView(context) {
```

2024-07-11 18:48 UTC, jeziellago commented on markdowntext/src/main/java/dev/jeziellago/compose/markdowntext/CustomTextView.kt
> +}
```suggestion
}

```

2024-07-12 08:36 UTC, HXavier21 commented on markdowntext/src/main/java/dev/jeziellago/compose/markdowntext/CustomTextView.kt
> +class CustomTextView(context: Context?) : AppCompatTextView(context!!) {
didn't notice that😢

2024-07-12 08:39 UTC, HXavier21 commented on markdowntext/src/main/java/dev/jeziellago/compose/markdowntext/CustomTextView.kt
> +}
cannot understand but ok

2024-07-12 12:56 UTC, jeziellago approved these changes

2024-07-12 13:21 UTC, HXavier21 commented
Find a fatal error, used a full-width punctuation in MainActivity while edit code in Github. Sorry for that.😭

2024-07-12 13:26 UTC, jeziellago approved these changes

2024-07-12 13:37 UTC, merged

2024-07-15 13:24 UTC, AleksandarIlic commented
@HXavier21 @jeziellago This changes broke text selection. It's impossible to select text now.

2024-07-15 13:33 UTC, HXavier21 commented
> @HXavier21 @jeziellago This changes broke text selection. It's impossible to select text now.

I'll check it right away😢

2024-07-15 14:09 UTC, HXavier21 commented
> @HXavier21 @jeziellago This changes broke text selection. It's impossible to select text now.

It seems that selecting text also needs to trigger a long press event, causing a conflict.
A workable but not good modification is：
```kotlin
when (isTextSelectable) {
    true -> TextView(factoryContext)
    false -> CustomTextView(factoryContext)
}.apply {
    ...
}
```
Another possible approach is to add control of `isTextSelectable` in `CustomTextView` and adapt the `MovementMethod` of selecting text in `OnTouchEvent`.
Are there any other methods?

2024-07-15 14:31 UTC, HXavier21 commented
Since enabling text selection means disabling the long press gesture, it has been proven in practice that the bug can be simply fixed by the following changes:

2024-07-15 15:30 UTC, jeziellago commented
@HXavier21 could open a PR fixing it?

2024-07-15 17:31 UTC, HXavier21 commented
> @HXavier21 could open a PR fixing it?
> In case you can't, I'll revert this change until we have a new and well-tested solution that doesn't break the current impl.

I'll open a PR right away, and I'd like to know if there are any bugs similar to this one🤔

2024-07-15 18:01 UTC, HXavier21 commented
> @HXavier21 could open a PR fixing it? In case you can't, I'll revert this change until we have a new and well-tested solution that doesn't break the current impl.

See #108